# brew 'docker'
brew 'ack'
# brew 'android-sdk'
brew 'ant'
brew 'elasticsearch'
brew 'elixir'
brew 'gmp'
brew 'httpie'
brew 'heroku'
brew 'hub'
brew 'htop'
brew 'nmap'
brew 'node'
brew 'postgres'
brew 'pow'
brew 'rbenv'
brew 'redis'
brew 'stow'
brew 'tmux'
brew 'vim'
brew 'yubikey-personalization'
brew 'xz'

cask '1password'
cask 'arduino'
cask 'atom'
cask 'caffeine'
cask 'disk-inventory-x'
cask 'firefox'
cask 'flux'
cask 'github-desktop'
cask 'gitx'
cask 'google-chrome'
cask 'gpgtools'
cask 'iterm2'
cask 'keka'
cask 'limechat'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'sublime-text'
cask 'spotify'
cask 'virtualbox'
cask 'webtorrent'
cask 'yubikey-neo-manager'
cask 'yubikey-personalization-gui'

