brew 'ack'
brew 'ant'
brew 'crystal-lang'
brew 'elasticsearch'
brew 'elixir'
brew 'gmp'
brew 'heroku'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'nmap'
brew 'node'
brew 'node@6'
brew 'phantomjs'
brew 'postgres'
brew 'pow'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'stow'
brew 'tmux'
brew 'vim'
brew 'xz'
brew 'yubikey-personalization'

cask 'arduino'
cask 'atom'
cask 'caffeine'
cask 'disk-inventory-x'
cask 'docker'
cask 'firefox'
cask 'flux'
cask 'ganache'
cask 'github-desktop'
cask 'google-chrome'
cask 'gpgtools'
cask 'iterm2'
cask 'keka'
cask 'limechat'
cask 'rowanj-gitx'
cask 'sketch'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text'
cask 'virtualbox'
cask 'webtorrent'
cask 'yubikey-neo-manager'
cask 'yubikey-personalization-gui'

mas "1Password", id: 443987910
mas "Caffeine", id: 411246225
mas "Cetus3D", id: 1190841558
mas "NordVPN", id: 1116599239
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
